name: huongviet.22web.org

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  DeployChangesToServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to the server 
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ftp://ftpupload.net:21/maymanagementtest.22web.org/htdocs
          user: b17_27686411
          password: hoangthanhbinh1994
