name: huongviet.22web.org

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  DeployChangesToServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to the server 
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ${{ secrets.HUONGVIET_FTP_URL }}
          user: ${{ secrets.TEST_FTP_USER }}
          password: ${{ secrets.TEST_FTP_PASSWORD }}
