name: management.mayapartment.com

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  DeployChangesToServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to the server 
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftpupload.net	
          username: b17_27686411
          password: hoangthanhbinh1994
          server-dir: maymanagementtest.22web.org/htdocs/