name: management.mayapartment.com

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  DeployChangesToServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to the server 
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ftpupload.net	
          user: b17_27686411
          password: hoangthanhbinh1994
          remoteDir: /vol13_1/byethost17.com/b17_27686411/maymanagementtest.22web.org