name: pkk.mayapartment.com 

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  DeployChangesToServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to the server 
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ${{ secrets.PKK_FTP_URL }}
          user: ${{ secrets.PKK_FTP_USER }}
          password: ${{ secrets.PKK_FTP_PASSWORD }}