# This is a basic workflow to help you get started with Actions

name: Sync all branches

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  Check out:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: test
        run: echo i am testing my run 
        
  Sync branches: 
    runs-on: ubuntu-latest
    steps:
      - name: Sync Test
        uses: tretuna/sync-branches@1.2.0
        with: 
          GITHUB_TOKEN: ${{secrets.GITHUBTOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "test"
      
