name: test-may.mayapartment.com

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  DeployChangesToServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install 
      - name: Deploy to the server 
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.mayapartment.com
          username: mayapart	
          password: BH++i++050994
          server-dir: test-may.mayapartment.com/